#include "raw_reader.hpp"
#include <map>
#include <array>
#include <iostream>
using namespace r2;
struct Sample {double value;std::size_t attempt;double time;std::size_t targets;};
json sample(const Sample& s){return {{"ms",s.value},{"attempt",s.attempt},{"capture_offset_ms",s.time},{"targets",s.targets}};}
json detail(const std::vector<Sample>& v){
 std::vector<double> values;for(auto s:v)values.push_back(s.value);auto result=distribution(values);
 auto sorted=v;std::sort(sorted.begin(),sorted.end(),[](auto a,auto b){return a.value<b.value||(a.value==b.value&&a.attempt<b.attempt);});
 for(auto [key,p]:std::initializer_list<std::pair<const char*,double>>{{"p95",.95},{"p99",.99}}){const auto rank=static_cast<std::size_t>(std::ceil(p*v.size()));result[std::string(key)+"_order"]={{"rank_1based",rank},{"upper_order_count",v.empty()?0:v.size()-rank+1},{"sample",v.empty()?json(nullptr):sample(sorted.at(rank-1))}};}
 result["largest_eight"]=json::array();for(std::size_t i=0;i<std::min<std::size_t>(8,v.size());++i)result["largest_eight"].push_back(sample(sorted[sorted.size()-1-i]));
 constexpr std::array<double,7> boundaries{0,100,500,1000,2000,5000,1e99};result["fixed_capture_windows"]=json::array();
 for(std::size_t i=1;i<boundaries.size();++i){std::vector<double> w;for(auto s:v)if(s.time>=boundaries[i-1]&&s.time<boundaries[i])w.push_back(s.value);result["fixed_capture_windows"].push_back({{"begin_ms",boundaries[i-1]},{"end_ms",i==boundaries.size()-1?json(nullptr):json(boundaries[i])},{"metrics",distribution(w)}});}
 return result;
}
int main(int argc,char** argv){try{
 require(argc==3||(argc==4&&std::string(argv[3])=="active"),"usage SOURCE NEW_REPORT [active]");const bool active=argc==4;fs::path source=argv[1],out=argv[2];require(!fs::exists(out),"existing report");json report;std::uint64_t normal_owner_max=0,normal_rgb_max=0;
 for(const auto& d:fs::directory_iterator(source)){
 const auto name=d.path().filename().string();if(!d.is_directory()||(!name.starts_with("aa-")&&!name.starts_with("stress-")))continue;
 const auto s=read(d.path()/"summary.json");auto frames=rows(d.path()/"frames.jsonl"),receipts=rows(d.path()/"receipts.jsonl"),releases=rows(d.path()/"releases.jsonl");require(frames.size()==s.at("attempts")&&receipts.size()==s.at("receipt_n")&&releases.size()==s.at("release_n"),"raw counts");
 const auto begin=frames.at(0).at("capture_complete_ns").get<std::int64_t>();std::map<std::string,std::vector<double>> m;std::map<std::string,std::vector<Sample>> details;json skips=json::array(),load=json::object();std::vector<double> accept_intervals;std::int64_t prior_owner=0;std::size_t consumed=0,owned=0,published=0,loads=0;
 for(std::size_t i=0;i<frames.size();++i){const auto& f=frames[i];require(f.at("attempt")==i+1,"frame sequence");published+=f.at("published").get<bool>();m["publish"].push_back(f.at("publish_cost_ns").get<double>()/1e6);const auto t=(f.at("capture_complete_ns").get<std::int64_t>()-begin)/1e6;const auto n=f.at("targets").get<std::size_t>();
 if(!f.at("owned"))skips.push_back({{"attempt",i+1},{"capture_offset_ms",t},{"published",f.at("published")},{"consumed",f.at("consumed")},{"targets",n}});
 if(f.at("consumed")){++consumed;loads+=n;const auto k=std::to_string(n);load[k]=load.value(k,0ULL)+1;auto value=(f.at("recognition_complete_ns").get<std::int64_t>()-f.at("recognition_start_ns").get<std::int64_t>())/1e6;m["recognition"].push_back(value);details["recognition"].push_back({value,i+1,t,n});}
 if(f.at("owned")){++owned;for(auto [k,a,b]:{std::tuple{"owner","owner_end_ns","owner_start_ns"},std::tuple{"capture_to_owner","owner_end_ns","capture_complete_ns"},std::tuple{"pre_accept_diagnostic_and_wait","owner_start_ns","recognition_complete_ns"}}){auto value=(f.at(a).get<std::int64_t>()-f.at(b).get<std::int64_t>())/1e6;m[k].push_back(value);details[k].push_back({value,i+1,t,n});}const auto now=f.at("owner_start_ns").get<std::int64_t>();if(prior_owner)accept_intervals.push_back((now-prior_owner)/1e6);prior_owner=now;}
 }
 require(consumed==s.at("consumed")&&owned==s.at("owner_seen")&&published==s.at("published"),"frame totals");
 for(const auto& f:frames){auto t=[&](const char* k){return f.at(k).get<std::int64_t>();};if(f.at("consumed"))require(t("capture_complete_ns")<=t("pixels_ready_ns")&&t("pixels_ready_ns")<=t("published_ns")&&t("published_ns")<=t("recognition_start_ns")&&t("recognition_start_ns")<=t("recognition_complete_ns"),"frame time order");if(f.at("owned"))require(t("recognition_complete_ns")<=t("owner_start_ns")&&t("owner_start_ns")<=t("owner_end_ns"),"owner time order");}
 for(const auto& r:receipts){auto seq=r.at("source_frame").get<std::size_t>();require(seq>0&&seq<=frames.size(),"receipt join");auto start=r.at("injection_start_ns").get<std::int64_t>(),end=r.at("injection_return_ns").get<std::int64_t>(),due=r.at("scheduled_ns").get<std::int64_t>();const double late=(start-due)/1e6;m["lateness"].push_back(late);m[std::array<const char*,3>{"down_lateness","move_lateness","up_lateness"}.at(r.at("phase").get<std::size_t>())].push_back(late);m["injection_call"].push_back((end-start)/1e6);m["capture_to_injection_all_phases"].push_back((start-frames[seq-1].at("capture_complete_ns").get<std::int64_t>())/1e6);}
 std::uint64_t requested=0,failed=0,unknown=0;for(std::size_t i=0;i<releases.size();++i){const auto& r=releases[i];require(r.at("call_index")==i,"release index");requested+=r.at("requested_ids").size();failed+=r.at("failed_ids").size();unknown+=r.at("unknown_ids").size();m["release_call"].push_back((r.at("return_ns").get<std::int64_t>()-r.at("start_ns").get<std::int64_t>())/1e6);}
 require(requested==s.at("release_requested_ids")&&failed==s.at("release_failed_ids")&&unknown==s.at("release_unknown_ids"),"release totals");for(auto k:{"recognition","owner","capture_to_owner","publish","lateness","down_lateness","move_lateness","up_lateness","injection_call","release_call","capture_to_injection_all_phases"})check(s.at("metrics_ms").at(k),m[k]);
 auto completion=read(d.path()/"archive/round-1/summary.json");std::map<std::string,std::uint64_t> counts,bytes;std::uint64_t logical=0,physical=0,event_rows=0;std::size_t ri=0,li=0;
 for(const auto& seg:completion.at("event_segments")){auto path=d.path()/"archive/round-1"/seg.at("path").get<std::string>();physical+=fs::file_size(path);for(auto j:rows(path)){++event_rows;auto size=j.dump().size()+1;logical+=size;auto kind=j.at("event").get<std::string>();++counts[kind];bytes[kind]+=size;j.erase("schema_version");j.erase("clock_domain");j.erase("round_id");if(kind=="game_touch_receipt")require(ri<receipts.size()&&j==receipts[ri++],"archive receipt content");if(kind=="game_release_report")require(li<releases.size()&&j==releases[li++],"archive release content");}}
 require(json(counts)==s.at("event_counts")&&ri==receipts.size()&&li==releases.size(),"archive counts");require(logical==s.at("journal_serialized_bytes")&&event_rows==s.at("journal_written"),"archive bytes");
 if(active){const auto& c=s.at("active_coverage");std::size_t body=0,down=0,move=0,up=0;int contact=-1;for(const auto& r:receipts){const int phase=r.at("phase");if(phase==0){++down;contact=r.at("contact_id");}else if(phase==1)++move;else ++up;require(r.at("contact_id")==contact&&r.at("success").get<bool>(),"active receipt identity/success");}for(const auto& f:frames)if(f.at("owned").get<bool>()&&f.at("body_current").get<bool>()&&f.at("active_contacts_after_poll")==1){++body;require(f.at("active_contact_id")==contact,"active witness identity");}for(const auto& r:releases)for(auto id:r.at("requested_ids"))require(id==contact,"active release identity");require(down==1&&move>=2&&up==0&&body>=2&&requested==1&&failed==0&&unknown==0,"active path coverage");require(c.at("covered")==true&&c.at("body_active_samples")==body&&c.at("down")==down&&c.at("move")==move&&c.at("up")==up&&c.at("release_requested_ids")==requested&&c.at("receipt_n")==receipts.size()&&c.at("release_n")==releases.size()&&s.at("contacts_at_exit")==0&&s.at("hard_gate")==true,"active summary denominator");}
 std::uint64_t disk=0;for(const auto& f:fs::recursive_directory_iterator(d.path()))if(f.is_regular_file())disk+=f.file_size();if(name.starts_with("aa-owner"))normal_owner_max=std::max(normal_owner_max,disk);if(name.starts_with("aa-rgb"))normal_rgb_max=std::max(normal_rgb_max,disk);
 auto& r=report["runs"][name];r={{"original_summary",s},{"raw_eof_verified",true},{"raw_metrics_recomputed",11},{"attempts",frames.size()},{"consumed",consumed},{"owned",owned},{"owner_ratio",owned/double(frames.size())},{"skips",skips},{"target_load_consumed",loads},{"target_count_histogram",load},{"owner_accept_intervals_ms",distribution(accept_intervals)},{"event_type_counts",counts},{"event_type_logical_bytes",bytes},{"archive_logical_bytes",logical},{"archive_physical_bytes",physical},{"run_disk_bytes",disk},{"capture_span_ms",(frames.back().at("capture_complete_ns").get<std::int64_t>()-begin)/1e6},{"all_metrics_raw",json::object()}};
 for(const auto& [k,v]:m)r["all_metrics_raw"][k]=distribution(v);for(const auto& [k,v]:details)r["order_and_windows"][k]=detail(v);
 r["final_four_attempts"]=json::array();for(std::size_t i=frames.size()>4?frames.size()-4:0;i<frames.size();++i)r["final_four_attempts"].push_back(frames[i]);
 }
 require(report["runs"].size()==(active?3:12),"run count");report["synthetic_order_sensitivity"]=json::array();for(auto n:{114,128,256,1024,2048}){json x={{"n",n},{"rank_p99",static_cast<int>(std::ceil(.99*n))},{"upper_order_count",n-static_cast<int>(std::ceil(.99*n))+1}};for(int c:{0,1,2,10,21}){std::vector<double> v(n,1);for(int i=0;i<std::min(c,n);++i)v[i]=100;x["fixed_high_samples"][std::to_string(c)]=distribution(v);}report["synthetic_order_sensitivity"].push_back(x);}
 report["prospective_capacity"]={{"warmup_attempts",256},{"measurement_attempts",2304},{"total_attempts",2560},{"principal_min_samples",2000},{"owner_r1_max_disk_bytes",normal_owner_max},{"rgb_r1_max_disk_bytes",normal_rgb_max},{"AA_owner_four_linear_projection_bytes",normal_owner_max*80},{"AA_rgb_four_linear_projection_bytes",normal_rgb_max*40},{"projection_is_not_a_hard_bound",true},{"new_root_limit_bytes",128*1024*1024},{"no_new_normal_runs",true}};
 report["interpretation"]={{"windows","fixed descriptive partitions of ALL original samples; no gate re-evaluation or discarded tails"},{"pre_accept_gap","recognition complete to owner start includes decision JSON enqueue, scheduling and prior work; cannot isolate causality"},{"os_trace","absent"},{"writer_enqueue_raw","absent: preserve source summaries only, not independently reconstructed"},{"independence","unknown; upper order count is NOT an effective independent sample size"}};
 save(out,report);std::cout<<report.at("prospective_capacity").dump()<<'\n';return 0;
 }catch(const std::exception& e){std::cerr<<e.what()<<'\n';return 1;}}
