#include "active_stimulus.hpp"
#include "raw_reader.hpp"
#include "../runtime_x11_p_r1/meter_touch.hpp"
#include <gtest/gtest.h>
using namespace pas;using namespace r2;
TEST(R2Order, ShortAndLongTailRanksAreExact){for(auto [n,upper]:{std::pair{114,2},std::pair{128,2},std::pair{256,3},std::pair{2048,21}}){EXPECT_EQ(n-static_cast<int>(std::ceil(.99*n))+1,upper);std::vector<double> v(n,1);v[0]=v[1]=100;EXPECT_EQ(distribution(v).at("p99"),n<=128?100:1);}}
TEST(R2Stimulus, BoundariesAreFixedAndBodyCannotBootstrap){auto s=active_stimulus(1,799*ms,0);ASSERT_EQ(s.targets.size(),1u);EXPECT_TRUE(s.targets[0].note.head_on_line);EXPECT_EQ(s.targets[0].evidence_ns,799*ms);EXPECT_EQ(s.targets[0].expires_ns,899*ms);s=active_stimulus(2,800*ms,0);EXPECT_TRUE(s.targets[0].note.held_body_evidence);EXPECT_FALSE(s.targets[0].crossing_ns);s=active_stimulus(3,1800*ms,0);EXPECT_FALSE(s.playing_gate);EXPECT_TRUE(s.targets.empty());FakeClock c;c.set(800*ms);r1::MeterTouch t(c,0);SessionGameOwner o(c,t,5,{15,35*ms,30*ms});o.start(1);o.accept(active_stimulus(1,c.now_ns(),0),true);o.poll();EXPECT_TRUE(t.receipts.empty());o.finish();EXPECT_FALSE(active_coverage(t.receipts,t.release_calls,0,t.contacts.size()).at("covered"));}
TEST(R2Active, SkippedStartupStillDownContinuesSameContactAndReleases){FakeClock c;r1::MeterTouch t(c,0);SessionGameOwner o(c,t,5,{15,35*ms,30*ms});o.start(1);std::size_t body=0;std::uint64_t seq=1;
 // Consumer intentionally misses the original first snapshot, starts at 400ms.
 for(Nanoseconds now=400*ms;now<=1840*ms;now+=32*ms){c.set(now);auto s=active_stimulus(seq++,now,0);o.accept(s,s.playing_gate);o.poll();if(now>=head_end&&now<visible_end&&!t.contacts.empty()){++body;EXPECT_EQ(t.contacts.size(),1u);}o.owner()->take_accepted_plans();o.owner()->take_plan_cancellations();o.scheduler()->take_notices();}
 o.finish();auto coverage=active_coverage(t.receipts,t.release_calls,body,t.contacts.size());EXPECT_TRUE(coverage.at("covered"))<<coverage.dump();EXPECT_EQ(coverage.at("receipt_n"),coverage.at("down").get<int>()+coverage.at("move").get<int>()+coverage.at("up").get<int>());EXPECT_EQ(coverage.at("down"),1);EXPECT_GE(coverage.at("body_active_samples"),2);EXPECT_EQ(coverage.at("release_requested_ids"),1);}
TEST(R2Active, StaleSnapshotDoesNotRelaxLeaseToForceCoverage){FakeClock c;c.set(500*ms);r1::MeterTouch t(c,0);SessionGameOwner o(c,t,5,{15,35*ms,30*ms});o.start(1);o.accept(active_stimulus(1,400*ms,0),true);o.poll();EXPECT_TRUE(t.receipts.empty());o.finish();EXPECT_FALSE(active_coverage(t.receipts,t.release_calls,0,0).at("covered"));}
TEST(R2Active, UnsupportedBodyNeverRenewsEvidenceOrMoves){FakeClock c;r1::MeterTouch t(c,0);SessionGameOwner o(c,t,5,{15,35*ms,30*ms});o.start(1);c.set(790*ms);o.accept(active_stimulus(1,c.now_ns(),0),true);o.poll();ASSERT_EQ(t.receipts.size(),1u);c.set(810*ms);auto s=active_stimulus(2,c.now_ns(),0);s.targets[0].note.held_body_evidence=false;o.accept(s,true);o.poll();EXPECT_EQ(t.receipts.size(),1u);c.set(890*ms);o.poll();EXPECT_TRUE(t.contacts.empty());o.finish();EXPECT_FALSE(active_coverage(t.receipts,t.release_calls,0,0).at("covered"));}
TEST(R2Active, UnknownDownNeverRetriesOrPassesCoverage){FakeClock c;r1::MeterTouch t(c,0);t.unknown_down=true;SessionGameOwner o(c,t,5,{15,35*ms,30*ms});o.start(1);c.set(400*ms);o.accept(active_stimulus(1,c.now_ns(),0),true);o.poll();c.set(432*ms);o.accept(active_stimulus(2,c.now_ns(),0),true);o.poll();EXPECT_EQ(t.receipts.size(),1u);EXPECT_THROW(o.finish(),std::runtime_error);t.release_all();EXPECT_FALSE(active_coverage(t.receipts,t.release_calls,0,0).at("covered"));}
TEST(R2Coverage, ZeroReceiptAggregateAndWrongReleaseDenominatorReject){EXPECT_FALSE(active_coverage({},std::vector<ReleaseReport>(1),12,0).at("covered"));FakeClock c;r1::MeterTouch t(c,0);t.inject({1,0,Phase::down,400,500,0,1});t.inject({1,0,Phase::move,410,500,0,2});t.inject({1,0,Phase::move,420,500,0,3});t.release_all();ASSERT_TRUE(active_coverage(t.receipts,t.release_calls,2,0).at("covered"));auto bad=t.release_calls;bad[0].requested_ids.clear();EXPECT_FALSE(active_coverage(t.receipts,bad,2,0).at("covered"));auto wrong=t.receipts;wrong[2].command.contact_id=1;EXPECT_FALSE(active_coverage(wrong,t.release_calls,2,0).at("covered"));EXPECT_FALSE(active_coverage(t.receipts,t.release_calls,0,0).at("covered"));bad=t.release_calls;bad[0].unknown_ids={0};EXPECT_FALSE(active_coverage(t.receipts,bad,2,0).at("covered"));}
