param([Parameter(Mandatory)][string]$SourceRoot,
      [Parameter(Mandatory)][string]$BuildRoot,
      [Parameter(Mandatory)][string]$StageName,
      [Parameter(Mandatory)][string]$ToolSnapshot,
      [Parameter(Mandatory)][string]$GateReceipt,
      [ValidateSet('Configure','Build','Test')][string]$Operation,
      [ValidateSet('Release','Debug')][string]$Configuration='Release',
      [string[]]$Options=@(),[string[]]$Inputs=@(),
      [ValidateRange(30,1800)][int]$TotalSeconds=900)
$ErrorActionPreference='Stop'
$taskRepo=[IO.Path]::GetFullPath((Join-Path $PSScriptRoot '../..'))
$SourceRoot=[IO.Path]::GetFullPath($SourceRoot)
$BuildRoot=[IO.Path]::GetFullPath($BuildRoot)
if($StageName -notmatch '^[a-z0-9-]{1,90}$'){throw 'stage-name'}
if(-not $BuildRoot.StartsWith((Join-Path $taskRepo 'out/'),[StringComparison]::OrdinalIgnoreCase)){throw 'build-root'}
if($Operation -eq 'Configure' -and (Test-Path -LiteralPath $BuildRoot)){throw 'fresh-build-root'}
if($Operation -ne 'Configure' -and -not (Test-Path -LiteralPath (Join-Path $BuildRoot 'CMakeCache.txt'))){throw 'missing-configure'}
$bundle=Join-Path $taskRepo ('out/windows-handoff/'+$StageName+'-inputs')
if(Test-Path -LiteralPath $bundle){throw 'fresh-input-root'}
[IO.Directory]::CreateDirectory($bundle)|Out-Null
$snapshot=Get-Content -LiteralPath $ToolSnapshot -Raw|ConvertFrom-Json
$bin=Join-Path ([IO.Path]::GetDirectoryName($ToolSnapshot)) 'bin'
$compilerFiles=@(Get-ChildItem -LiteralPath $bin -File -Recurse|ForEach-Object FullName)
foreach($f in $snapshot.files){
  if((Get-FileHash -LiteralPath $f.copy -Algorithm SHA256).Hash.ToLowerInvariant() -cne $f.sha256){throw 'tool-snapshot-changed'}
}
$cmake='C:\Users\wurre\AppData\Local\Programs\Python\Python310\Lib\site-packages\cmake\data\bin\cmake.exe'
$ctest=Join-Path ([IO.Path]::GetDirectoryName($cmake)) 'ctest.exe'
$ninja='C:\Users\wurre\AppData\Local\Programs\Python\Python310\Scripts\ninja.exe'
$vcvars='C:\Program Files (x86)\Microsoft Visual Studio\18\BuildTools\VC\Auxiliary\Build\vcvars64.bat'
$exe=$cmake
switch($Operation){
  Configure {$nativeArgs=@('-S',$SourceRoot,'-B',$BuildRoot,'-G','Ninja',('-DCMAKE_MAKE_PROGRAM='+$ninja),('-DCMAKE_CXX_COMPILER='+$bin+'\cl.exe'),('-DCMAKE_LINKER='+$bin+'\link.exe'),('-DCMAKE_AR='+$bin+'\lib.exe'),('-DCMAKE_BUILD_TYPE='+$Configuration),'-DCMAKE_MSVC_DEBUG_INFORMATION_FORMAT=Embedded')+$Options}
  Build {$nativeArgs=@('--build',$BuildRoot,'--parallel','4')+$Options}
  Test {$exe=$ctest;$nativeArgs=@('--test-dir',$BuildRoot,'--output-on-failure','--no-tests=error','--timeout','60','--output-junit',(Join-Path $bundle 'junit.xml'))+$Options}
}
# These are literal cmd arguments generated by this local adapter. Refuse cmd
# expansion characters instead of treating JSON serialization as shell quoting.
foreach($v in @($exe,$bin,$vcvars)+$nativeArgs){if($v -match '["%\r\n]'){throw 'literal-cmd-argument'}}
$command='"'+$exe+'" '+(($nativeArgs|ForEach-Object {'"'+$_+'"'}) -join ' ')
$cmdPath=Join-Path $bundle ($Operation.ToLowerInvariant()+'.cmd')
$lines=@('@echo off',('echo TRACE '+$Operation+' entry [%cmdcmdline%]'),('call "'+$vcvars+'" -vcvars_ver=14.51 >nul'),
 'set "PAS_LOCAL_EXIT=%errorlevel%"','echo TRACE vcvars END exit=%PAS_LOCAL_EXIT%',
 'if not "%PAS_LOCAL_EXIT%"=="0" exit /b %PAS_LOCAL_EXIT%',('set "PATH='+$bin+';%PATH%"'),
 $command,'set "PAS_LOCAL_EXIT=%errorlevel%"',('echo TRACE '+$Operation+' END exit=%PAS_LOCAL_EXIT%'),('"C:\Users\wurre\.cache\codex-runtimes\codex-primary-runtime\dependencies\native\powershell\pwsh.exe" -NoProfile -Command "[Threading.Thread]::Sleep(750)"'),'exit /b %PAS_LOCAL_EXIT%')
[IO.File]::WriteAllText($cmdPath,($lines -join "`r`n")+"`r`n",[Text.UTF8Encoding]::new($false))
$spec=@{stage_root=(Join-Path $taskRepo ('out/windows-handoff/'+$StageName));stage=$StageName;
 exe=$env:ComSpec;argv=@('/d','/s','/c',$cmdPath);native_exit=0;runner_exit=0;total_s=$TotalSeconds;
 stream_cap=16777216;inputs=@($PSCommandPath,$cmdPath,$exe,$ninja,$vcvars,$ToolSnapshot)+$compilerFiles+$Inputs;
 environment=@{VSCMD_SKIP_SENDTELEMETRY='1';VC_DISABLE_SQM='1';MSBUILDDISABLENODEREUSE='1'}}
$specPath=Join-Path $bundle 'spec.json'
[IO.File]::WriteAllText($specPath,($spec|ConvertTo-Json -Depth 12),[Text.UTF8Encoding]::new($false))
& (Join-Path $taskRepo 'tools/zero_miss_windows/invoke.ps1') -Specification $specPath -GateReceipt $GateReceipt
exit $LASTEXITCODE
