target_include_directories(pas PRIVATE "${CMAKE_BINARY_DIR}/generated")
if(NOT X11_REPO)
  message(FATAL_ERROR "X11_REPO required for isolated offline harness")
endif()
add_executable(x11_cost "${X11_REPO}/apps/runtime_x11_p/main.cpp")
target_link_libraries(x11_cost PRIVATE pas_core psapi)
target_compile_options(x11_cost PRIVATE /W4 /EHsc /utf-8 /bigobj)
add_executable(x11_pending_tests "${X11_REPO}/apps/runtime_x11_p/pending_tests.cpp")
target_include_directories(x11_pending_tests PRIVATE "${X11_REPO}/apps/frame_review")
target_link_libraries(x11_pending_tests PRIVATE pas_core GTest::gtest_main)
target_compile_options(x11_pending_tests PRIVATE /W4 /EHsc /utf-8 /bigobj)
