param([ValidateSet('Prepare','Finalize')][string]$Phase='Prepare')
$ErrorActionPreference='Stop'
$repoPath=[IO.Path]::GetFullPath((Join-Path $PSScriptRoot '../..'))
$campaignPath=Join-Path $repoPath 'measurements/game-assist/2026-09-30-m0-manual-continue'
$batchPath=Join-Path $campaignPath 'hold-ownership-x10d-o-bvi-r1'
$oldPath=Join-Path $campaignPath 'hold-ownership-x10d-o-bvi'
function ReadJson($p){Get-Content -LiteralPath $p -Raw|ConvertFrom-Json}
function Bytes($p){if(Test-Path -LiteralPath $p){[long](Get-ChildItem -LiteralPath $p -File -Recurse|Measure-Object Length -Sum).Sum}else{0L}}
function Entry($p){$f=Get-Item -LiteralPath $p;@{path=$f.FullName;bytes=$f.Length;sha256=(Get-FileHash -LiteralPath $p).Hash.ToLowerInvariant()}}
function TextJson($v){($v|ConvertTo-Json -Depth 24)+"`n"}
function Save($name,$v){$p=Join-Path $batchPath $name;if(Test-Path -LiteralPath $p){throw "exists: $p"};[IO.File]::WriteAllText($p,(TextJson $v),[Text.UTF8Encoding]::new($false))}
$pre=ReadJson "$batchPath/pre-execution-binding.json";$controller=ReadJson "$oldPath/controller-review/controller-receipt.json"
if($Phase -eq 'Prepare'){
 foreach($f in @($pre.source)+@($pre.inputs)+@($pre.source_copy)+@($pre.dependencies_before)){$a=Entry $f.path;if($a.sha256 -ne $f.sha256 -or $a.bytes -ne $f.bytes){throw 'frozen binding mismatch'}}
 $natural=ReadJson "$batchPath/control-natural-exit.json";$nonzero=ReadJson "$batchPath/control-nonzero-exit.json"
 $memberDeps=@();foreach($r in @($natural,$nonzero)){foreach($m in $r.snapshots[0].members){$a=Entry $m.image;$a.mode='observed root executable fingerprint; not assembly/system closure';$memberDeps+=,$a}}
 Save 'input-manifest.json' @{schema=1;inputs=$pre.inputs;original_oracle_unchanged=$true;original_cases=69;original_supplemental=22;r1_cases=20;schema_controls=4;coverage_rows=1128;provenance_diff=(Entry "$batchPath/typed-provenance-diff.json");executed=$false}
 Save 'binary-manifest.json' @{schema=1;candidate_binaries=@();candidate_compiles=0;configure_probes=@();configure_count=0;out_root="$repoPath/out/x10d-o-bvi-r1";observed_maintenance_roots=$memberDeps;candidate_dependency_closure='not compiled; unverified'}
 Save 'dependency-manifest.json' @{schema=1;status='uncompiled source partial';dependencies=$pre.dependencies_before;observed_member_images=$memberDeps;candidate_compiled_inputs=@();candidate_dlls=@();closure_limits=@('No candidate/configure executed: no compiled include/link closure','Installed MSVC/CRT/tool/nlohmann fingerprints only; existing original frozen header kit referenced and protected','MSVC/SDK/STL/CRT/system DLL complete closure not copied or verified','PowerShell Add-Type/Roslyn/runtime assembly closure not claimed','Two natural root identities only; owned-child negative control not run','No Debug/ASan providers executed')}
 Save 'control-summary.json' @{schema=1;declared=3;executed=2;aggregate_pass=$false;runner_repairs_used=1;runner_repairs_remaining=0;natural_native_exit=$natural.exit_code;natural_tool_exit=0;nonzero_native_exit=$nonzero.exit_code;nonzero_tool_exit=1;both_natural_quiescence=($natural.natural_quiescence -and $nonzero.natural_quiescence);both_identity_trusted=($natural.identity_trusted -and $nonzero.identity_trusted);both_streams_completed=($natural.streams_completed -and $nonzero.streams_completed);both_cleanup_zero=($natural.cleanup_zero -and $nonzero.cleanup_zero);active_final=@($natural.active_final,$nonzero.active_final);negative_owned_child='not executed';stop='runner full batch literal remains original4I; R1 receipt verification failed; nonzero control wrongly executed after failed verification';relocation=(Entry "$batchPath/artifact-relocation.json");new_configure_allowed=$false;original_4I_residual_members='unknown'}
 Save 'delivery-status.json' @{schema=1;date='2026-10-04';timezone='Asia/Taipei';status='platform_tool_partial';stop='runner receipt-root control failed; mandatory stop before owned-child control/configure';source_family='BVI-1';source_findings_addressed=6;source_verified_by_execution=$false;original_top_vectors=20;original_expanded_cases=69;original_supplemental=22;r1_cases=20;schema_controls=4;planned_case_layer_instances=356;actual_case_layer_instances=0;assertions_executed=0;candidate_compiles=0;candidate_binaries=0;release_configure=0;release_build=0;tests='not run';rgb='not run';typed='not run';lifecycle='not run';e2e='not run';debug='not run';asan='not run';sizeof_metadata_probes='not measured';png_audits=0;png_frames=0;full_replay=0;runtime_cost_stress=0;live=0;tool_repairs=1;controls=2;controls_pass=$false;original_oracle_changed=$false;core_algorithm_verdict='unverified; no executed counterexample';runtime_adoption=$false;touch_backend=$false;next_dispatch=$false;png_copies=0;old_data_deleted=0;wrong_root_new_files_relocated=8;baseline='C36h tint1';main='50/27/11 donor/live0';suppression='OFF';P='excluded';X12='not-ready';chapter_denominator='unknown';song_unlocks='unknown'}
 Write-Output 'prepared partial manifests; no native execution'
 exit
}
$after=ReadJson "$batchPath/protection-after.json"
if($after.mismatches.Count -or $after.protected_count -ne 2039 -or $after.old_git_paths.Count -ne 479 -or $after.head -ne $controller.head -or $after.index_sha256 -ne $controller.index_sha256){throw 'final preservation invalid'}
foreach($f in $pre.source){$a=Entry $f.path;if($a.sha256 -ne $f.sha256 -or $a.bytes -ne $f.bytes){throw 'frozen execution source changed'}}
$external=@(Get-ChildItem -LiteralPath $PSScriptRoot -File|ForEach-Object{Entry $_.FullName})
$external+=@(Get-ChildItem -LiteralPath "$repoPath/docs" -File -Filter 'HOLD_OWNERSHIP_X10D_O_BVI_R1_*'|ForEach-Object{Entry $_.FullName})
$outFiles=@();if(Test-Path -LiteralPath "$repoPath/out/x10d-o-bvi-r1"){$outFiles=@(Get-ChildItem -LiteralPath "$repoPath/out/x10d-o-bvi-r1" -Recurse -File|ForEach-Object{Entry $_.FullName})}
$files=@(Get-ChildItem -LiteralPath $batchPath -File -Recurse|Where-Object{$_.Name -notin @('artifact-ledger.json','final-receipt.json')}|ForEach-Object{Entry $_.FullName})
Save 'artifact-ledger.json' @{schema=1;files=$files;external=$external;out=$outFiles;self_and_final_receipt_excluded=$true;count_method='entry logical length; every failed artifact retained';old_inputs_references=$pre.inputs;original_protection=(Entry "$batchPath/protection-after.json")}
$batchBase=Bytes $batchPath;$campaignBase=Bytes $campaignPath;$externalBytes=[long]($external|Measure-Object bytes -Sum).Sum;$newOut=[long]($outFiles|Measure-Object bytes -Sum).Sum
if($campaignBase-$batchBase -ne $controller.capacity.campaign_physical){throw 'original campaign bytes changed'}
if((Bytes "$repoPath/out/x10d-o-bvi") -ne 374705){throw 'original out bytes changed'}
$head=(& git -C $repoPath rev-parse HEAD).Trim();$index=(Get-FileHash -LiteralPath "$repoPath/.git/index").Hash.ToLowerInvariant()
$allPaths=@(& git -C $repoPath -c core.quotepath=false ls-files --cached --others --exclude-standard)
$newPaths=@($allPaths|Where-Object{$_ -like 'research/x10d_o_bvi_r1/*' -or $_ -like 'docs/HOLD_OWNERSHIP_X10D_O_BVI_R1_*'})
$free=(Get-PSDrive C).Free;$utc=[DateTime]::UtcNow.ToString('o');$selfLength=0L;$stable=$false
for($iteration=0;$iteration -lt 12;$iteration++){
 $r1Batch=$batchBase+$selfLength;$campaign=$campaignBase+$selfLength
 $development=4144966+$r1Batch+$externalBytes;$batchCharged=$development+605130
 $aggregate=$campaign+45307809+72115+9546+54056+11851+104033+12289+$externalBytes;$out=374705+$newOut
 if($development -gt 58720256 -or $batchCharged -gt 67108864 -or $aggregate -gt 8589934592 -or $out -gt 268435456 -or $free -lt 5704253440){throw 'shared capacity cap'}
 $v=[ordered]@{schema=1;date='2026-10-04';timezone='Asia/Taipei';settled_utc=$utc;decision='4I-R1 source repair delivered, mandatory tool partial stop; unverified implementation';head=$head;index_sha256=$index;original_git_paths=479;new_git_paths=$newPaths.Count;total_git_paths=$allPaths.Count;original_dirty_unchanged=$true;protected_original_files=2039;controller_sources_rehashed=2031;protection_mismatches=0;frozen_binding_checks=109;source_finding_repairs=6;source_behavior_verified=$false;old_oracle_sha256='90f8680c4362d07a718ac2bb7142b37396871b7ffd81523a06ddd8a685ec5425';oracle_changed=$false;runner_repairs=1;controls_declared=3;controls_executed=2;controls_pass=$false;negative_child_control='not run';configure=0;build=0;candidate_binaries=0;tests=0;debug=0;asan=0;png_audits=0;full_replay=0;live=0;algorithm_verdict='unverified, no executed core counterexample';adopted=$false;next_dispatch=$false;source_files=$external.Count-2;artifact_ledger=(Entry "$batchPath/artifact-ledger.json");dependency_manifest=(Entry "$batchPath/dependency-manifest.json");input_manifest=(Entry "$batchPath/input-manifest.json");binary_manifest=(Entry "$batchPath/binary-manifest.json");protection_after=(Entry "$batchPath/protection-after.json");control_summary=(Entry "$batchPath/control-summary.json");capacity=[ordered]@{method='conservative entry logical bytes';development_carry=4144966;r1_batch=$r1Batch;r1_external=$externalBytes;r1_development=$r1Batch+$externalBytes;development_charged=$development;development_cap=58720256;development_remaining=58720256-$development;controller_carry=605130;controller_new=0;controller_charged=605130;controller_cap=8388608;controller_remaining=7783478;shared_batch_charged=$batchCharged;shared_batch_cap=67108864;shared_batch_remaining=67108864-$batchCharged;campaign_carry=8234791454;campaign_physical=$campaign;prior=45307809;carried_external_O_development=72115;carried_external_O_controller=9546;carried_external_4R_development=54056;carried_external_4R_controller=11851;carried_external_4I_development=104033;carried_external_4I_controller=12289;aggregate_carry=8280363153;aggregate_charged=$aggregate;aggregate_cap=8589934592;aggregate_remaining=8589934592-$aggregate;out_carry=374705;out_new=$newOut;out_total=$out;out_cap=268435456;out_remaining=268435456-$out;disk_free=$free;minimum_free=5704253440;png_copies=0;old_data_deleted=0;own_misplaced_entries_relocated=8};self_bytes=$selfLength;self_hash_excluded=$true}
 $text=TextJson $v;$actualLength=[Text.UTF8Encoding]::new($false).GetByteCount($text)
 if($actualLength -eq $selfLength){$stable=$true;break};$selfLength=$actualLength
}
if(-not $stable){throw 'receipt size fixed point failed'}
Save 'final-receipt.json' $v
if((Bytes $batchPath) -ne $v.capacity.r1_batch -or (Bytes $campaignPath) -ne $v.capacity.campaign_physical){throw 'post-write capacity mismatch'}
$entry=Entry "$batchPath/final-receipt.json"
Write-Output (@{status='platform_tool_partial';protected=2039;mismatches=0;original_paths=479;new_paths=$newPaths.Count;development=$development;r1_development=$r1Batch+$externalBytes;aggregate=$aggregate;aggregate_remaining=8589934592-$aggregate;out=$out;receipt=$entry}|ConvertTo-Json -Depth 6)
