#include <nlohmann/json.hpp>
#include <array>
#include <filesystem>
#include <fstream>
#include <iostream>
#include <map>
#include <set>
using J=nlohmann::json;namespace fs=std::filesystem;
J read(const fs::path&p,std::size_t cap){if(fs::file_size(p)>cap)throw std::runtime_error("file bound");std::ifstream f(p);return J::parse(f);}
template<class F> std::size_t stream(const fs::path&p,F fn){if(fs::file_size(p)>1073741824ull+65536)throw std::runtime_error("stream bound");std::ifstream f(p,std::ios::binary);std::string line;std::size_t n=0;while(std::getline(f,line)){if(++n>65536||line.size()>262144||line.empty())throw std::runtime_error("row bound");fn(J::parse(line));}if(!f.eof())throw std::runtime_error("stream EOF");return n;}
int main(int argc,char**argv){try{if(argc!=3||fs::exists(argv[2]))throw std::runtime_error("fresh report");const fs::path p=argv[1];auto r=read(p,1024*1024);const bool pixel=r.at("schema")=="pas.prelive-current-pixels.v1";J errors=J::array();auto check=[&](bool b,const char*s){if(!b)errors.push_back(s);};
 const bool loss=!pixel&&(r.at("writer_fault").get<bool>()||r.at("writer_drops").get<int>()!=0||r.at("journal_admission_failed").get<bool>());
 std::size_t consumed=0,owned=0,published=0,written=0;std::set<int> written_frames;
 if(!pixel){auto a=read(p.string()+".attempts.json",12*1024*1024);check(a.size()==r.at("requested"),"attempt_length");long long prior=0;for(std::size_t i=0;i<a.size();++i){const auto&s=a[i];check(s.at("attempt")==i+1,"attempt_sequence");auto capture=s.at("capture").get<long long>();check(capture>0&&capture>=prior,"capture_order");prior=capture;const bool pub=s.at("published_ok"),con=s.at("consumed"),own=s.at("owned");published+=pub;consumed+=con;owned+=own;written+=s.at("writer_ok").get<bool>();if(s.at("writer_ok").get<bool>())written_frames.insert(int(i+1));check(!con||pub,"consume_unpublished");check(!own||con,"own_unconsumed");if(con)check(s.at("journal_enqueue_complete")>=s.at("owner_complete")&&s.at("owner_complete")>=s.at("capture"),"chain_time_order");if(own)check(s.at("observer_ns").get<long long>()>=0&&s.at("hook_ns").get<long long>()>=0&&s.at("owner_ns").get<long long>()>=0,"compute_time_order");}
 check(consumed==r.at("consumed")&&owned==r.at("owner_seen")&&published==r.at("published"),"reported_counts");check(published+r.at("pool_drops").get<std::size_t>()==a.size(),"publish_denominator");check(written==r.at("writer_ok"),"writer_count");
 }else{const auto n=stream(p.string()+".rows.jsonl",[&](const J&s){++consumed;check(s.at("ordinal").get<int>()>0,"pixel_ordinal");});check(n==r.at("processed"),"pixel_rows_count");}
 using Key=std::pair<int,std::uint64_t>;std::map<Key,std::uint64_t> plans;std::vector<J> receipts;std::array<bool,5> active{};std::map<std::string,int> basis;std::set<int> complete;std::size_t releases=0,failed=0;int window=0;J release_unknown=J::array();
 const auto rows=stream(p.string()+(pixel?".events.jsonl":".journal.jsonl"),[&](const J&e){const auto type=e.value("event","");if(pixel&&e.value("window",0)!=window){check(std::none_of(active.begin(),active.end(),[](bool x){return x;}),"window_reset_active");window=e.at("window");}if(type=="own_accepted_plan"){Key key{window,e.at("intent")};auto note=e.at("note").get<std::uint64_t>();if(plans.contains(key))check(plans[key]==note,"intent_note_changed");plans[key]=note;++basis[e.at("basis").get<std::string>()];}
 if(type=="own_injection_receipt"){if(receipts.size()>=20000)throw std::runtime_error("receipt bound");receipts.push_back(e);const int id=e.at("contact"),phase=e.at("phase");check(id>=0&&id<5&&phase>=0&&phase<=2,"contact_phase_bounds");check(e.at("injection_return")>=e.at("injection_start"),"receipt_time_order");if(id<0||id>=5)return;if(!e.at("success").get<bool>()){++failed;if(phase==0)active[id]=true;}else if(phase==0){check(!active[id],"contact_duplicate_down");active[id]=true;}else{check(active[id],"move_up_no_own_down");if(phase==2)active[id]=false;}}
 if(type=="release_receipt"){++releases;for(int id:e.at("requested")){if(id<0||id>=5){check(false,"release_contact_bound");continue;}const auto&f=e.at("failed");const auto&u=e.at("unknown");if(std::find(f.begin(),f.end(),id)==f.end()&&std::find(u.begin(),u.end(),id)==u.end())active[id]=false;}if(!e.at("failed").empty()||!e.at("unknown").empty())release_unknown.push_back(e);}
 if(type=="complete_current_chain"){const int id=e.at("frame");check(complete.insert(id).second,"complete_frame_duplicate");}
 });
 std::array<int,3> phases{};for(const auto&e:receipts){Key key{pixel?e.at("window").get<int>():0,e.at("intent")};check(plans.contains(key)||loss,"receipt_plan_join_missing");int phase=e.at("phase");if(phase>=0&&phase<3)++phases[phase];}
 if(!loss){check(phases[0]==r.at("own_down")&&phases[1]==r.at("own_move")&&phases[2]==r.at("own_up"),"receipt_phase_counts");if(!pixel){check(rows==r.at("journal_records"),"journal_rows_count");check(complete==written_frames,"complete_frame_join");check(failed==r.at("injection_failed"),"backend_failure_count");check(fs::file_size(p.string()+".journal.jsonl")<=r.at("journal_admitted_bytes"),"journal_physical_bound");}}
 if(r.at("release_verified").get<bool>())check(std::none_of(active.begin(),active.end(),[](bool x){return x;}),"final_contact_active");
 J out={{"schema","pas.prelive-independent-integrity.v1"},{"path",p.string()},{"integrity",errors.empty()},{"errors",errors},{"complete_prefix_evidence",!loss},{"declared_writer_loss",loss},{"event_rows",rows},{"receipts",receipts.size()},{"phases",phases},{"release_calls",releases},{"unknown_release",release_unknown},{"plan_basis_rows",basis},{"all_input_processed",pixel?r.at("processed")==r.at("frames"):r.at("attempts")==r.at("requested")},{"device_endpoints",0},{"game_adoption","unknown"}};std::ofstream f(argv[2]);f<<out.dump(2)<<'\n';if(!f)throw std::runtime_error("write");std::cout<<(errors.empty()?"integrity verified":"integrity failed")<<'\n';return 0;
 }catch(const std::exception&e){std::cerr<<e.what()<<'\n';return 2;}}
