$ErrorActionPreference='Stop'
$repoPath=(Resolve-Path "$PSScriptRoot/../..").Path
$campaignPath="$repoPath/measurements/game-assist/2026-09-30-m0-manual-continue"
$batchPath="$campaignPath/hold-ownership-x10d-o"
$outPath="$repoPath/out/x10d-o"
function Hash($p){(Get-FileHash -LiteralPath $p -Algorithm SHA256).Hash.ToLowerInvariant()}
function Bytes($p){[long](Get-ChildItem -LiteralPath $p -File -Recurse|Measure-Object Length -Sum).Sum}
function Save($name,$v){[IO.File]::WriteAllText("$batchPath/$name",($v|ConvertTo-Json -Depth 60)+"`n",[Text.UTF8Encoding]::new($false))}
if(Test-Path "$batchPath/final-receipt.json"){throw 'delivery sealed; do not overwrite'}
$before=Get-Content "$batchPath/workspace-before.json" -Raw|ConvertFrom-Json
$checked=@();$errors=@()
foreach($f in $before.protected){$p="$repoPath/$($f.path)";if(!(Test-Path -LiteralPath $p) -or (Hash $p) -ne $f.sha256){$errors+=$p};$checked+=@{kind='original_git_file';path=$p;sha256=$f.sha256}}
$parent=Get-Content "$batchPath/parent-binding.json" -Raw|ConvertFrom-Json
foreach($f in @($parent.x10c_checked)+@($parent.x1_checked)){if((Hash $f.path) -ne $f.sha256){$errors+=$f.path};$checked+=@{kind='frozen';path=$f.path;sha256=$f.sha256}}
$exportItems=@();foreach($role in @('reference','candidate')){$e=Get-Content "$batchPath/$role-export.json" -Raw|ConvertFrom-Json;foreach($f in $e.files){$p="$outPath/$role/$($f.path)";if((Hash $p) -ne $f.sha256){$errors+=$p};$exportItems+=@{role=$role;path=$p;bytes=$f.bytes;sha256=$f.sha256}}}
$packet=Get-Content "$batchPath/rgb-packet.json" -Raw|ConvertFrom-Json
foreach($f in $packet.frames){if((Hash $f.path) -ne $f.png_sha256){$errors+=$f.path};$checked+=@{kind='selected_original_png';path=$f.path;sha256=$f.png_sha256}}
foreach($pair in @(@('index.jsonl',"$($packet.recording)/index.jsonl",$packet.index_sha256),@('trace',$packet.trace_path,$packet.trace_sha256),@('witness',$packet.witness_path,$packet.witness_sha256))){if((Hash $pair[1]) -ne $pair[2]){$errors+=$pair[1]};$checked+=@{kind='selected_input';path=$pair[1];sha256=$pair[2]}}
if((git rev-parse HEAD) -ne $before.head -or (Hash "$repoPath/.git/index") -ne $before.index_sha256){$errors+='HEAD/index'}
git diff --quiet HEAD -- src include CMakeLists.txt
if($LASTEXITCODE -ne 0){$errors+='production diff'}
$newPaths=@(git -c core.quotepath=false ls-files --cached --others --exclude-standard|Where-Object {$_ -notin @($before.protected.path)})
foreach($p in $newPaths){if($p -notlike 'research/x10d_o/*' -and $p -notlike 'tools/x10d_o/*' -and $p -notlike 'docs/HOLD_OWNERSHIP_X10D_O_*'){$errors+="unexpected path $p"}}
$asan=Get-Content "$batchPath/build-asan-exit.json" -Raw|ConvertFrom-Json
$remaining=@();foreach($d in $asan.descendants){$p=Get-CimInstance Win32_Process -Filter "ProcessId=$($d.pid)" -ErrorAction SilentlyContinue;if($p -and [string]$p.CreationDate -eq $d.creation){$remaining+=$d.pid}}
if($remaining.Count){$errors+='cleanup residual'}
Save 'protection-after.json' @{head=(git rev-parse HEAD);index_sha256=Hash "$repoPath/.git/index";protected_git_file_count=$before.protected.Count;checked_count=$checked.Count;checked=$checked;isolated_exports=$exportItems;new_paths=$newPaths;unexpected=$errors;unchanged=($errors.Count -eq 0);asan_cleanup=@{tracked_descendants=$asan.descendants.Count;remaining_matching_pid_creation=$remaining;verification='read-only after command-scoped stop; no global process changes'};ignored_raw_scope='selected196 PNG and chosen frozen/input bindings, not exhaustive all original ignored files'}
if($errors.Count){throw 'protection failed; no delivery signed'}
$tests=@();foreach($spec in @(@('original-release',207,0),@('reference-red',11,8),@('candidate-contract',11,1),@('owner-controls',8,0))){
 [xml]$x=Get-Content "$batchPath/$($spec[0]).xml" -Raw;$t=$x.testsuites;$cases=@($t.testsuite.testcase);$fail=@($cases|Where-Object {$null -ne $_.failure});$skip=@($cases|Where-Object {$null -ne $_.skipped});if([int]$t.tests -ne $spec[1] -or $fail.Count -ne $spec[2] -or [int]$t.errors -ne 0 -or [int]$t.disabled -ne 0 -or $skip.Count){throw 'XML denominator mismatch'}
 $tests+=@{name=$spec[0];tests=$cases.Count;pass=$cases.Count-$fail.Count;fail=$fail.Count;errors=0;disabled=0;skip=0;failed_cases=@($fail|ForEach-Object {"$($_.classname).$($_.name)"});xml_sha256=Hash "$batchPath/$($spec[0]).xml"}
}
$commands=@();foreach($f in Get-ChildItem $batchPath -Filter '*-command.json'){$name=$f.BaseName.Replace('-command','');$exit=if(Test-Path "$batchPath/$name-exit.json"){Get-Content "$batchPath/$name-exit.json" -Raw|ConvertFrom-Json}else{$null};$commands+=@{name=$name;command_sha256=Hash $f.FullName;exit=$exit}}
$freezePath="$batchPath/freeze";New-Item -ItemType Directory $freezePath|Out-Null
$sourceItems=@();$sourcePaths=@($newPaths)
$sourcePaths+=@('apps/frame_review/x10c_contact_replay.cpp','tests/contact_replay_tests.cpp','vcpkg.json','vcpkg-configuration.json')
$sourcePaths+=@(Get-ChildItem "$repoPath/apps/frame_review" -Filter '*.hpp' -File|ForEach-Object {$_.FullName.Substring($repoPath.Length+1).Replace('\','/')})
foreach($p in @($sourcePaths|Sort-Object -Unique)){$dest="$freezePath/repo/$p";New-Item -ItemType Directory (Split-Path $dest) -Force|Out-Null;Copy-Item -LiteralPath "$repoPath/$p" -Destination $dest;$sourceItems+=@{path=$p;actual="$repoPath/$p";snapshot=$dest;bytes=(Get-Item $dest).Length;sha256=Hash $dest}}
foreach($f in $exportItems){$rel=$f.path.Substring($outPath.Length+1).Replace('\','/');$dest="$freezePath/export/$rel";New-Item -ItemType Directory (Split-Path $dest) -Force|Out-Null;Copy-Item -LiteralPath $f.path -Destination $dest;$f|Add-Member -NotePropertyName snapshot -NotePropertyValue $dest}
$binaries=@();foreach($dir in @('build/Release','asan/Debug')){foreach($f in Get-ChildItem "$outPath/$dir" -File|Where-Object {$_.Extension -in @('.exe','.dll','.lib')}){$dest=$null;if($f.Extension -ne '.lib'){$dest="$freezePath/binary/$dir/$($f.Name)";New-Item -ItemType Directory (Split-Path $dest) -Force|Out-Null;Copy-Item -LiteralPath $f.FullName -Destination $dest};$binaries+=@{path=$f.FullName;snapshot=$dest;bytes=$f.Length;sha256=Hash $f.FullName;status=if($dir -eq 'asan/Debug'){'failed_build_unverified_tests_not_executed'}else{'release_executed_or_linked'}}}}
$dependencies=@();$depPaths=@('out/vcpkg_installed/x64-windows/lib/z.lib','out/vcpkg_installed/x64-windows/lib/gtest.lib','out/vcpkg_installed/x64-windows/lib/gtest_main.lib','out/vcpkg_installed/x64-windows/debug/lib/z.lib','out/vcpkg_installed/x64-windows/debug/lib/gtest.lib','out/vcpkg_installed/x64-windows/debug/lib/gtest_main.lib','out/vcpkg_installed/vcpkg/status')
foreach($rel in $depPaths){$p="$repoPath/$rel";if(Test-Path $p){$dependencies+=@{path=$p;sha256=Hash $p;bytes=(Get-Item $p).Length}}}
foreach($p in @('C:/Program Files (x86)/Microsoft Visual Studio/18/BuildTools/VC/Tools/MSVC/14.51.36231/bin/Hostx64/x64/cl.exe','C:/Program Files (x86)/Microsoft Visual Studio/18/BuildTools/VC/Tools/MSVC/14.51.36231/bin/Hostx64/x64/link.exe',(Get-Command cmake).Source)){$dependencies+=@{path=$p;sha256=Hash $p;bytes=(Get-Item $p).Length}}
$caches=@();foreach($mode in @('build','asan')){$p="$outPath/$mode/CMakeCache.txt";$dest="$freezePath/$mode-CMakeCache.txt";Copy-Item -LiteralPath $p -Destination $dest;$caches+=@{path=$p;snapshot=$dest;sha256=Hash $p}}
$parts=@('core','game','game_tracking','game_motion','game_session','analysis','adb','config','game_tracking_methods','touch_evidence','session_archive','session_pixel_clips','journal','game_tracking_shadow')
$compiled=@($parts|ForEach-Object {"out/x10d-o/reference/src/$_.cpp"})+@('out/x10d-o/reference/tests/game_tests_offline.cpp','out/x10d-o/reference/tests/game_tracking_tests.cpp','out/x10d-o/reference/tests/game_session_tests.cpp','out/x10d-o/reference/tests/core_tests.cpp','tests/contact_replay_tests.cpp','apps/frame_review/x10c_contact_replay.cpp','research/x10d_o/contract_tests.cpp','research/x10d_o/reference.cpp','research/x10d_o/candidate.cpp','research/x10d_o/owner_controls.cpp','research/x10d_o/packet_audit.cpp')
[IO.File]::WriteAllText("$batchPath/runtime-policy.patch",'',[Text.UTF8Encoding]::new($false))
Save 'delivery-binding.json' @{schema=1;source=$sourceItems;exports=$exportItems;binaries=$binaries;dependencies=$dependencies;caches=$caches;compiled_cpp=$compiled;compiled_runtime_lineage='reference only; candidate helper links same reference core';core_policy_patch_bytes=0;source_snapshot_scope='complete project-owned compiled cpp and exposed headers; optional unused reader header snapshots retained';dependency_limit='installed libraries/tool executables/cache hashes and runtime DLL snapshots, not entire Windows SDK/STL/system DLL closure';post_binding_build_allowed=$false}
$reader=Get-Content "$batchPath/pixel-support-audit.json" -Raw|ConvertFrom-Json
Save 'judgment.json' @{schema=1;package='X10d-O';implemented=@('isolated BCC-v1 hypothesis','independent RGB render contracts','unmodified C36h FakeClock controls','196-frame current-support audit');runtime_candidate_implemented=$false;self_verified_release=$tests;pending_controller=$true;rejected=@('BCC-v1 exclusive ownership from bilateral continuity and one anchor');retained=@('pixel-support diagnostic scan','negative evidence');gameplay='Unknown';human_gold_added=0;suppression='OFF';pending_hook=$false;baseline_adopted=$false;full_behavior=@{new_replay_attempts=0;failed_attempts=0;reference_actions=$null;candidate_actions=$null;unmatched_reference=$null;unmatched_candidate=$null;first_scene_divergence=$null;first_history_divergence=$null;first_owner_divergence=$null;first_contact_divergence=$null;cancel_return_rebuild=$null;lost_opportunities=$null;release=$null;contacts_at_exit=$null;trace_on_off='not_run';reason='family rejected before integration and conditional replay gate'};packet=@{png=196;consumed=195;skip=1;bank_candidates=$reader.all_bank_candidates;holds=$reader.hold_candidates;supported=$reader.bilateral_supported;not_supported=$reader.hold_candidates-$reader.bilateral_supported};not_completed=@('Debug-ASan execution','reliable physical ownership strategy','end-to-end candidate old-tail/new-front and late alignment rollout','new full action comparison','gameplay feedback');commands=$commands;engineering_failures=@('prepare Git quoted path','configure exit serialization','packet compile string/JSON conversion','packet original-cadence null handling','ASan descendant quiescence');execution_tool_repairs=1;initialize_engineering_corrections=1;no_extra_agents_chats_messages_goals_automation_commit_push=$true}
$ledger=@();foreach($f in Get-ChildItem $batchPath -File -Recurse){$ledger+=@{path=$f.FullName.Substring($batchPath.Length+1).Replace('\','/');bytes=$f.Length;sha256=Hash $f.FullName}}
Save 'artifact-ledger.json' @{files=$ledger;self_capacity_receipt_hash_excluded=$true;note='All files existing before ledger; ledger/capacity/final receipt byte sizes included in settled capacity. Source snapshot contains immutable expected binding.'}
$external=@($newPaths|ForEach-Object {Get-Item -LiteralPath "$repoPath/$_"});$externalBytes=[long]($external|Measure-Object Length -Sum).Sum
$last=-1
for($i=0;$i -lt 10;++$i){
 $batchBytes=Bytes $batchPath;$outBytes=Bytes $outPath;$campaignBytes=Bytes $campaignPath;$priorBytes=Bytes "$repoPath/measurements/research-next-20261001";$charged=$batchBytes+$externalBytes;$aggregate=$campaignBytes+$priorBytes+$externalBytes
 $capacity=@{batch_physical=$batchBytes;external_new_files=$externalBytes;development_charged=$charged;development_cap=234881024;controller_reserve=33554432;batch_total_cap=268435456;out_bytes=$outBytes;out_cap=1073741824;campaign_physical=$campaignBytes;prior=$priorBytes;aggregate_charged=$aggregate;aggregate_cap=8589934592;aggregate_remaining=8589934592-$aggregate;disk_free=(Get-PSDrive C).Free;external_files=@($external|ForEach-Object {@{path=$_.FullName;bytes=$_.Length;sha256=Hash $_.FullName}});png_copies=0;old_data_deleted=0}
 Save 'capacity.json' $capacity
 Save 'final-receipt.json' @{schema=1;date='2026-10-04';timezone='Asia/Taipei';decision='negative family rejected; partial engineering self-verification; pending independent controller';head=$before.head;implemented_runtime_candidate=$false;release_original=@{pass=207;fail=0;skip=0;real_rgb_frames=27};reference_adapter=@{pass=3;fail=8};candidate_hypothesis=@{pass=10;fail=1;rejected=$true};owner_controls=@{pass=8;fail=0};asan=@{build_contract_passed=$false;failure='descendants_nonquiescent';tests_executed=0;cleanup_remaining=0};png_verified=196;full_replay_attempts=0;live=0;human_gold_added=0;protected_original_git_files=$before.protected.Count;protection_passed=$true;new_paths=$newPaths;capacity=$capacity;self_hash_excluded=$true}
 $settled=Bytes $batchPath;if($settled -eq $last){break};$last=$settled
}
$actual=Bytes $batchPath;$receipt=Get-Content "$batchPath/final-receipt.json" -Raw|ConvertFrom-Json
if($receipt.capacity.batch_physical -ne $actual -or $receipt.capacity.development_charged -gt 234881024 -or $receipt.capacity.out_bytes -gt 1073741824 -or $receipt.capacity.aggregate_charged+33554432 -gt 8589934592){throw 'settled capacity mismatch or reserve unavailable'}
Write-Output "sealed batch=$actual charged=$($receipt.capacity.development_charged) out=$($receipt.capacity.out_bytes) aggregate=$($receipt.capacity.aggregate_charged) protected=$($before.protected.Count)"
