target_include_directories(pas PRIVATE "${CMAKE_BINARY_DIR}/generated")
set(R1_ROOT "${X11_REPO}/apps/runtime_x11_p_r1")
add_executable(x11_cost "${R1_ROOT}/main.cpp")
target_link_libraries(x11_cost PRIVATE pas_core psapi)
target_compile_options(x11_cost PRIVATE /W4 /EHsc /utf-8 /bigobj)
add_executable(x11_pending_tests "${X11_REPO}/apps/runtime_x11_p/pending_tests.cpp")
target_include_directories(x11_pending_tests PRIVATE "${X11_REPO}/apps/frame_review")
target_link_libraries(x11_pending_tests PRIVATE pas_core GTest::gtest_main)
target_compile_options(x11_pending_tests PRIVATE /W4 /EHsc /utf-8 /bigobj)
add_executable(x11_r1_tests "${R1_ROOT}/tests.cpp")
target_link_libraries(x11_r1_tests PRIVATE pas_core GTest::gtest_main)
target_compile_options(x11_r1_tests PRIVATE /W4 /EHsc /utf-8 /bigobj)
add_executable(x11_gate "${R1_ROOT}/gate.cpp")
target_link_libraries(x11_gate PRIVATE nlohmann_json::nlohmann_json)
target_compile_options(x11_gate PRIVATE /W4 /EHsc /utf-8 /bigobj)
if(R1_ASAN)
 foreach(t pas_core x11_cost x11_r1_tests x11_pending_tests)
  target_compile_options(${t} PRIVATE /fsanitize=address /D_DISABLE_VECTOR_ANNOTATION /D_DISABLE_STRING_ANNOTATION /D_DISABLE_OPTIONAL_ANNOTATION)
 endforeach()
 foreach(t x11_cost x11_r1_tests x11_pending_tests)
  target_link_options(${t} PRIVATE /INCREMENTAL:NO /LIBPATH:${CMAKE_BINARY_DIR}/asan_support/lib)
 endforeach()
endif()
