. "$PSScriptRoot/r3-common.ps1"
if(Test-Path "$batchPath/final-summary.json"){throw 'already finalized'}
$before=Get-Content "$batchPath/workspace-before.json" -Raw|ConvertFrom-Json
$source=Get-Content "$batchPath/source-binding-before-cost.json" -Raw|ConvertFrom-Json
$deps=Get-Content "$batchPath/compiled-dependency-freeze.json" -Raw|ConvertFrom-Json
foreach($j in @($source,$deps)){foreach($f in $j.files){if((R3Hash $f.path) -ne $f.sha256 -or (Get-Item -LiteralPath $f.path).Length -ne $f.bytes){throw "frozen changed $($f.path)"}}}
foreach($f in $before.formal_files){if((R3Hash $f.path) -ne $f.sha256){throw 'formal changed'}}
if((git rev-parse HEAD) -ne $before.head -or (git branch --show-current) -ne $before.branch -or (@(git worktree list --porcelain) -join '|') -cne ($before.worktrees -join '|')){throw 'git identity'}
$preserved=0;$appends=@();foreach($f in $before.dirty_files){
 if($f.path -like '*runtime_x11_p_r3*' -or $f.path -like '*runtime-x11-p-r3*' -or $f.path -eq 'tools/r3-common.ps1'){continue}
 if($f.path -in @('docs/PROJECT_STATUS_NEXT_STEPS_20261001.md','docs/C36H_FORWARD_EXECUTION_PLAN_20261003.md')){
  $bytes=[IO.File]::ReadAllBytes("$repoPath/$($f.path)");$prefix=[byte[]]$bytes[0..($f.bytes-1)];$h=[Security.Cryptography.SHA256]::Create();$hash=[BitConverter]::ToString($h.ComputeHash($prefix)).Replace('-','').ToLowerInvariant();$h.Dispose();if($hash -ne $f.sha256){throw 'document preimage prefix'};$appends+=@{path=$f.path;old_sha256=$f.sha256;new_sha256=(R3Hash "$repoPath/$($f.path)");prefix_preserved=$true}
 }else{if((R3Hash "$repoPath/$($f.path)") -ne $f.sha256){throw "prior dirty $($f.path)"};++$preserved}
}
R3Save 'workspace-after.json' @{head=(git rev-parse HEAD);branch=(git branch --show-current);worktrees=@(git worktree list --porcelain);status=@(git status --short);formal_diff=@(git diff HEAD -- src include CMakeLists.txt);formal_files_unchanged=$before.formal_files.Count;original_dirty_files_unchanged=$preserved;authorized_document_appends=$appends;commit_push=$false;emulator_ADB_live_model_goal_chat_automation=$false}
New-Item -ItemType Directory "$batchPath/documents-delivery" | Out-Null
foreach($n in @('RUNTIME_X11_P_R3_PROTOCOL_20261003.md','RUNTIME_X11_P_R3_RESULT_20261003.md','RUNTIME_X11_P_R3_HANDOFF_20261003.md','PROJECT_STATUS_NEXT_STEPS_20261001.md','C36H_FORWARD_EXECUTION_PLAN_20261003.md')){Copy-Item -LiteralPath "$repoPath/docs/$n" -Destination "$batchPath/documents-delivery/$n"}
$q=Get-Content "$batchPath/qualification.json" -Raw|ConvertFrom-Json
$tests=Get-Content "$batchPath/tests-final-collected.json" -Raw|ConvertFrom-Json
$runs=@();$totals=@{};foreach($r in $q.runs){$s=Get-Content "$batchPath/$($r.name)/summary.json" -Raw|ConvertFrom-Json;$runs+=@{name=$r.name;role=$r.role;gate=$r;summary=$s;audit_sha256=(R3Hash "$batchPath/$($r.name)-audit.json")};foreach($k in @('attempts','published','consumed','owner_seen','pool_drops','consumer_skips','decision_skips','receipt_n','down','move','up','late_over_15ms','release_n','release_requested_ids','release_failed_ids','release_unknown_ids','accepted_plans','coverage','canceled','rejected','journal_attempts','journal_written','journal_serialized_bytes')){$totals[$k]+=[long]$s.$k}}
$normalBytes=0;foreach($r in $q.runs){$normalBytes+=R3Bytes "$batchPath/$($r.name)"};$engineering=(R3Bytes $batchPath)-$normalBytes;if($engineering+8MB -gt 96MB){throw 'engineering/ledger reserve'}
$files=@();$paths=[Collections.Generic.HashSet[string]]::new([StringComparer]::OrdinalIgnoreCase)
foreach($root in @($batchPath,$outPath,"$repoPath/apps/runtime_x11_p_r3")){foreach($f in Get-ChildItem -LiteralPath $root -File -Recurse){if($f.Name -notin @('artifact-ledger.json','final-summary.json')){[void]$paths.Add($f.FullName)}}}
foreach($f in Get-ChildItem -LiteralPath "$repoPath/tools" -File|Where-Object {$_.Name -like '*runtime-x11-p-r3*' -or $_.Name -eq 'r3-common.ps1'}){[void]$paths.Add($f.FullName)}
foreach($p in $paths|Sort-Object){$len=(Get-Item -LiteralPath $p).Length;$entry=@{path=$p;physical_file_bytes=$len;logical_file_bytes=$len;sha256=(R3Hash $p);allocated_NTFS_bytes='Unknown';newline_encoding='binary/unspecified';LF_count=$null;CRLF_count=$null;LF_normalized_bytes=$null}
 if([IO.Path]::GetExtension($p) -in @('.json','.jsonl','.md','.cpp','.hpp','.ps1','.txt','.log','.xml','.cmake','.vcxproj','.filters','.tlog','.map')){$b=[IO.File]::ReadAllBytes($p);$utf16=$b.Length -ge 2 -and $b[0] -eq 255 -and $b[1] -eq 254;$text=if($utf16){[Text.Encoding]::Unicode.GetString($b)}else{[Text.Encoding]::UTF8.GetString($b)};$crlf=[regex]::Matches($text,"`r`n").Count;$lf=[regex]::Matches($text,"(?<!`r)`n").Count;$entry.newline_encoding=if($utf16){'UTF16LE'}else{'UTF8/ASCII'};$entry.LF_count=$lf;$entry.CRLF_count=$crlf;$entry.LF_normalized_bytes=$len-$crlf*$(if($utf16){2}else{1})};$files+=$entry
}
R3Save 'artifact-ledger.json' @{files=$files;exclusions=@('ledger self SHA in final-summary','final-summary root has no self-reference');mutable_workspace_documents_bound=$false;documents='immutable batch documents-delivery/pre-delivery snapshots';logical_physical_definition='logical_file_bytes and physical_file_bytes are file lengths; LF_normalized_bytes separately removes CR bytes, NTFS allocation Unknown'}
$summary=@{state=$q.state;delivery='交付完成，待總控獨立驗收';controller_acceptance='pending independent acceptance';head=$before.head;branch=$before.branch;date='2026-10-03 Asia/Taipei';worktree_count=1;strategy='C36h tint1 baseline/main50 donor; unchanged pending-only8-line hook; suppression OFF';new_runtime_exe=$false;runtime_B0_sha256=$source.runtime_B0_sha256;runtime_B1_sha256=$source.runtime_B1_sha256;profile_reference=$source.profile_reference;profile_sha256=$source.profile_sha256;source_bindings=$source.files.Count;compiled_dependencies=$deps.files.Count;source_binding_sha256=(R3Hash "$batchPath/source-binding-before-cost.json");compiled_dependency_sha256=(R3Hash "$batchPath/compiled-dependency-freeze.json");inverse_files=57;formal_files_unchanged=$before.formal_files.Count;prior_dirty_files_unchanged=$preserved;original_document_prefixes_preserved=$true;tests=$tests;qualification=$q;AA_runs=$q.AA_runs;ABBA_runs=$q.ABBA_runs;stress_runs=0;runs=$runs;totals=$totals;failed_builds=2;engineering_repair_used_before_cost=1;measurement_repair_after_cost=0;rebuild_after_freeze=$false;no_emulator_ADB_live_model_chat_goal_automation_commit_push=$true;old_bindings_after_sha256=(R3Hash "$batchPath/old-freeze-verified-after.json");original_live_unlisted_compiled_SHA='Unknown';instrumentation_default_difference='new symmetric archive statistics65536 only vs R1 meter16384; default runtime no meter clock/delay; new timing raw/admission/writer work retained';Verified=@('new bounded collector10/10 in B0,B1,ASan and full bridge','source/map/dependency/inverse/old SHA protection','actual long-window raw full denominators and all14 metric families','qualification stopped at necessary gate; no retry');Strong_inference=@('shared archive instrumentation preserves measured deterministic public strategy behavior');Hypothesis=@('background OS/diagnostic competition may affect tail variability; no causal trace');Unknown=@('effective independent samples','candidate cost when AA insufficient','whole manual-session real capture/RPC/device adoption','14 lost opportunity tradeoffs/77Miss/cross-song');artifact_ledger_entries=$files.Count;artifact_ledger_sha256=(R3Hash "$batchPath/artifact-ledger.json");capacity=@{}}
$p="$batchPath/final-summary.json";for($i=0;$i -lt 8;++$i){[IO.File]::WriteAllText($p,($summary|ConvertTo-Json -Depth 95)+"`n",[Text.UTF8Encoding]::new($false));$cap=R3Capacity;$cap.normal_raw_bytes=$normalBytes;$cap.engineering_bytes=$cap.batch_bytes-$normalBytes;$cap.normal_slots_max=24;$cap.normal_run_reserve_bytes=80MB;$cap.normal_reserve_bytes=1920MB;$cap.engineering_limit_bytes=96MB;$cap.old_start_bytes=$before.initial_old_bytes;$old=$summary.capacity|ConvertTo-Json -Compress;$summary.capacity=$cap;if($old -ceq ($cap|ConvertTo-Json -Compress)){break}}
if($i -eq 8){throw 'summary fixed point'}
$actual=R3Capacity;$saved=Get-Content $p -Raw|ConvertFrom-Json;foreach($k in @('batch_bytes','out_bytes','old_campaign_plus_prior_bytes','combined_bytes')){if($actual.$k -ne $saved.capacity.$k){throw 'actual byte totals'}}
if($saved.capacity.engineering_bytes -gt 96MB){throw 'engineering actual'}
Write-Output "R3 delivery complete; state=$($q.state); AA=$($q.AA_runs); ABBA=$($q.ABBA_runs); exact summary SHA=$(R3Hash $p)"
$saved.capacity|ConvertTo-Json
