. "$PSScriptRoot/r3-common.ps1"
if(Test-Path "$batchPath/source-binding-before-cost.json"){throw 'already frozen'}
if(!(Test-Path "$batchPath/tests-final-collected.json") -or !(Test-Path "$batchPath/old-freeze-verified-before.json")){throw 'tests/old binding prerequisite'}
Copy-Item -LiteralPath "$repoPath/docs/RUNTIME_X11_P_R3_PROTOCOL_20261003.md" -Destination "$batchPath/protocol-before-cost.md"
$env3=@{os=Get-CimInstance Win32_OperatingSystem|Select-Object Caption,Version,BuildNumber;cpu=Get-CimInstance Win32_Processor|Select-Object Name,NumberOfCores,NumberOfLogicalProcessors;computer=Get-CimInstance Win32_ComputerSystem|Select-Object TotalPhysicalMemory;power_plan=@(powercfg /getactivescheme);environment_control='no affinity/priority/power changes; background load uncontrolled';clock='same HostClock QPC; raw frequency per run';qpc_frequency_before_cost=[Diagnostics.Stopwatch]::Frequency;compiled_configuration='MSVCv145 Release for all cost; ASan deterministic tests only';capacity=(R3Capacity);test_order=@('B0 tests10','B0 bridge','B1 tests10','B1 bridge','ASan tests10');cost_order=@('AA rgb1-4','AA owner1-4','freeze noise','ABBA rgb batch1,2 then owner1,2 only if all AA necessary gates pass');new_stress=0;R2_active_reference="$campaignPath/runtime-x11-p-r2/active-raw-analysis.json"}
R3Save 'method-environment-before-cost.json' $env3
$inputs=[Collections.Generic.HashSet[string]]::new([StringComparer]::OrdinalIgnoreCase);$projects=@();$maps=@()
foreach($role in @('B0','B1','asan')){
 $build="$outPath/build-$role";$config=if($role -eq 'asan'){'Debug'}else{'Release'}
 foreach($f in Get-ChildItem -LiteralPath $build -Filter '*.read.1.tlog' -File -Recurse){foreach($line in [IO.File]::ReadAllLines($f.FullName)){if($line -match '^[A-Z]:\\' -and (Test-Path -LiteralPath $line -PathType Leaf)){[void]$inputs.Add($line)}}}
 foreach($f in Get-ChildItem -LiteralPath $build -Filter '*.vcxproj' -File){[xml]$x=Get-Content -LiteralPath $f.FullName -Raw;$ns=[Xml.XmlNamespaceManager]::new($x.NameTable);$ns.AddNamespace('m','http://schemas.microsoft.com/developer/msbuild/2003');$groups=@($x.SelectNodes('//m:ItemDefinitionGroup',$ns)|Where-Object Condition -Match "$config\|x64");$projects+=@{role=$role;path=$f.FullName;settings=@($groups|ForEach-Object OuterXml)};[void]$inputs.Add($f.FullName);foreach($g in $groups){if($g.Link.AdditionalDependencies){foreach($p in $g.Link.AdditionalDependencies.Split(';')){if([IO.Path]::IsPathRooted($p) -and (Test-Path -LiteralPath $p -PathType Leaf)){[void]$inputs.Add($p)}}}}}
 [void]$inputs.Add("$build/CMakeCache.txt")
 foreach($target in @('r3_meter','r3_tests')){$p="$build/$config/$target.map";$s=[IO.File]::ReadAllText($p);if($s -match 'pas_core:session_archive\.obj' -or $s -notmatch 'SessionArchive.*session_archive\.obj'){throw 'archive selection map'};$maps+=@{role=$role;target=$target;path=$p;sha256=(R3Hash $p);new_archive_object=$true;original_library_archive_object_loaded=$false}}
}
foreach($p in @((Get-Command cmake).Source,'C:/Program Files (x86)/Microsoft Visual Studio/18/BuildTools/VC/Tools/MSVC/14.51.36231/bin/Hostx64/x64/cl.exe','C:/Program Files (x86)/Microsoft Visual Studio/18/BuildTools/VC/Tools/MSVC/14.51.36231/bin/Hostx64/x64/link.exe')){[void]$inputs.Add($p)}
$deps=@();foreach($p in $inputs|Sort-Object){$deps+=@{path=$p;bytes=(Get-Item -LiteralPath $p).Length;sha256=(R3Hash $p)}}
R3Save 'compiled-dependency-freeze.json' @{files=$deps;projects=$projects;link_maps=$maps;scope='actual R3 CL/link read tlogs plus libraries/compiler; unchanged core transitive inputs independently verified in R1';core_recompiled=$false}
$files=@();foreach($f in Get-ChildItem -LiteralPath "$repoPath/apps/runtime_x11_p_r3" -File -Recurse){$files+=@{path=$f.FullName;bytes=$f.Length;sha256=(R3Hash $f.FullName)}}
foreach($f in Get-ChildItem -LiteralPath "$repoPath/tools" -File|Where-Object {$_.Name -like '*runtime-x11-p-r3*' -or $_.Name -eq 'r3-common.ps1'}){$files+=@{path=$f.FullName;bytes=$f.Length;sha256=(R3Hash $f.FullName)}}
foreach($p in @("$repoPath/apps/runtime_x11_p_r1/gate_contract.hpp","$batchPath/protocol-before-cost.md","$batchPath/method-environment-before-cost.json","$batchPath/capacity-allocation-before-engineering.json","$batchPath/tests-collected.json","$batchPath/tests-final-collected.json","$batchPath/pre-delivery-PROJECT_STATUS_NEXT_STEPS_20261001.md","$batchPath/pre-delivery-C36H_FORWARD_EXECUTION_PLAN_20261003.md")){$files+=@{path=$p;bytes=(Get-Item -LiteralPath $p).Length;sha256=(R3Hash $p)}}
foreach($f in Get-ChildItem -LiteralPath $outPath -File -Recurse|Where-Object Extension -in '.exe','.dll'){$files+=@{path=$f.FullName;bytes=$f.Length;sha256=(R3Hash $f.FullName)}}
R3Save 'source-binding-before-cost.json' @{files=$files;new_runtime_exe=$false;runtime_B0_sha256=(R3Hash "$repoPath/out/x11-p-r1/runtime-B0/pas.exe");runtime_B1_sha256=(R3Hash "$repoPath/out/x11-p-r1/runtime-B1/pas.exe");profile_reference="$campaignPath/runtime-x11-p-r1/x12-profile-preview.json";profile_sha256=(R3Hash "$campaignPath/runtime-x11-p-r1/x12-profile-preview.json");strategy_delta='unchanged8-line pending-only; suppression OFF';collector_delta='symmetric bounded long window; all timing samples retained; archive sample limit65536';compiled_dependency_sha256=(R3Hash "$batchPath/compiled-dependency-freeze.json")}
New-Item -ItemType Directory "$batchPath/source-snapshot" | Out-Null
Copy-Item -LiteralPath "$repoPath/apps/runtime_x11_p_r3" -Destination "$batchPath/source-snapshot/apps" -Recurse
New-Item -ItemType Directory "$batchPath/source-snapshot/tools" | Out-Null
foreach($f in Get-ChildItem -LiteralPath "$repoPath/tools" -File|Where-Object {$_.Name -like '*runtime-x11-p-r3*' -or $_.Name -eq 'r3-common.ps1'}){Copy-Item -LiteralPath $f.FullName -Destination "$batchPath/source-snapshot/tools/$($f.Name)"}
R3Save 'measurement-engineering-repair.json' @{budget_max=1;used_before_cost=1;failed_builds=2;causes=@('GTest EXPECT macros on same line duplicate LINE labels','C++20 string/JSON rewritten != overload; explicit get<string>');failed_logs=@('build-B0-1.log','build-B0-2.log');initial_source='engineering-source-initial';cost_before_repairs=0;cost_retries=0;repair_after_freeze_forbidden=$true;all_pre_cost_source_changes_frozen=$true}
Write-Output "R3 frozen: sources=$($files.Count), dependencies=$($deps.Count); no rebuild"
